List<String> placesList = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington, D.C.',
  'Boston',
  'El Paso',
  'Nashville',
  'Detroit',
  'Oklahoma City',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Long Beach',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Raleigh',
  'Miami',
  'Rome',
  'Paris',
  'Berlin',
  'London',
  'Madrid',
  'Barcelona',
  'Amsterdam',
  'Vienna',
  'Prague',
  'Zurich',
  'Munich',
  'Hamburg',
  'Frankfurt',
  'Brussels',
  'Dublin',
  'Copenhagen',
  'Stockholm',
  'Oslo',
  'Helsinki',
  'Dubai',
  'Abu Dhabi',
  'Doha',
  'Riyadh',
  'Jeddah',
  'Cairo',
  'Istanbul',
  'Lahore',
  'Karachi',
  'Islamabad',
  'Rawalpindi',
  'Peshawar',
  'Quetta',
  'Faisalabad',
  'Multan',
  'Hyderabad (Pakistan)',
  'Sialkot',
  'Bahawalpur',
  'Gujranwala',
  'Gujrat',
  'Sargodha',
  'Sheikhupura',
  'Mardan',
  'Sukkur',
  'Dera Ghazi Khan',
  'Muzaffarabad',
  'Skardu',
  'Murree',
  'Swat',
  'Hunza',
  'Gilgit',
  'Naran',
  'Kaghan',
  'Chitral',
  'Fairy Meadows',
  'Shogran',
  'Neelum Valley',
];
